name: pipeline

on: [ push, pull_request ]

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Codebase laden
              uses: actions/checkout@v3
            - name: Node.js einrichten
              uses: actions/setup-node@v5
              with:
                node-version: '22'
            - name: Abhängigkeiten installieren und Linting ausführen
              run: |
                npm ci
                npm run lint

    testing:
        runs-on: ubuntu-latest
        needs: linting
        steps:
            - name: Codebase laden
              uses: actions/checkout@v3
            - name: Node.js einrichten
              uses: actions/setup-node@v5
              with:
                node-version: '22'
            - name: Abhängigkeiten installieren und Tests ausführen
              run: |
                npm ci
                npm test

    deploy:
        runs-on: ubuntu-latest
        needs: testing
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Git Pull vom Hostsystem aus ausführen und Docker Compose neu starten
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.VPS_SSH_KEY }}
                port: 22
                script: |
                  cd private-cloud/
                  git pull
                  docker compose down
                  docker compose up -d --build
