name: pipeline

on: [ push, pull_request ]

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v5
              with:
                node-version: '22'
            - run: npm ci
            - run: npm run lint
    
    deploy:
        runs-on: ubuntu-latest
        needs: linting
        if: github.ref == 'refs/heads/main'
        steps:
            - name: auf den VPS hochladen
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.VPS_IP }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.VPS_SSH_KEY }}
                port: 22
                script: |
                  cd private-cloud/
                  cloud-update
